name: Docker Build and Push

on:
  push:
    branches:
      - main  # Workflow akan berjalan saat ada push ke branch "main"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Step 3: Set up Docker Buildx (untuk build performa tinggi)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 4: Cache Docker layers (opsional, untuk mempercepat build berikutnya)
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    # Step 5: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t cutsula/gorecipe:${{ github.sha }} .

    # Step 6: Push Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push cutsula/gorecipe:${{ github.sha }}
